#!/usr/bin/env python3
"""
generate_fr3_controller.py

Generates FR3 controller boilerplate:
  - HPP: include/fr3_husky_controller/<snake>.hpp
  - CPP: src/<snake>.cpp

Also patches:
  - CMakeLists.txt        : adds .cpp to add_library block
  - fr3_husky_plugin.xml  : adds class entry
  - config/fr3_ros_controllers.yaml : adds left_<name>, right_<name>, dual_<name> entries
                                      with manipulator_command_interface = <control_mode>

Usage:
  python3 generate_fr3_controller.py MyNewController --control_mode effort
  python3 generate_fr3_controller.py MyNewController --control_mode position --force
"""

import argparse
import re
from pathlib import Path
from typing import Tuple


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def script_pkg_root() -> Path:
    return Path(__file__).resolve().parent


def to_snake(name: str) -> str:
    s = name.strip()
    s = re.sub(r"[\-\s]+", "_", s)
    s = re.sub(r"[^0-9a-zA-Z_]", "_", s)
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", s)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    s = s.lower()
    s = re.sub(r"_+", "_", s).strip("_")
    if not s:
        raise ValueError("Name becomes empty after normalization.")
    if s[0].isdigit():
        s = f"ctrl_{s}"
    return s


def to_camel(snake: str) -> str:
    parts = [p for p in snake.split("_") if p]
    out = "".join(p[:1].upper() + p[1:] for p in parts)
    if not out:
        raise ValueError("Cannot create CamelCase class name.")
    if out[0].isdigit():
        out = f"Ctrl{out}"
    return out


def ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Code templates
# ---------------------------------------------------------------------------

def render_hpp(class_name: str) -> str:
    return f"""#pragma once

#include <string>
#include <chrono>
#include <array>
#include <memory>
#include <mutex>
#include <cassert>
#include <cmath>
#include <exception>
#include <map>
#include <functional>
#include <vector>
#include <algorithm>
#include <numeric>
#include <sstream>
#include <type_traits>
#include <Eigen/Eigen>

#include <rclcpp/rclcpp.hpp>
#include <ament_index_cpp/get_package_share_directory.hpp>
#include <controller_interface/controller_interface.hpp>
#include <controller_interface/helpers.hpp>
#include <controller_manager_msgs/srv/list_hardware_interfaces.hpp>
#include <hardware_interface/loaned_command_interface.hpp>
#include <hardware_interface/types/hardware_interface_type_values.hpp>
#include <rclcpp_lifecycle/state.hpp>
#include "lifecycle_msgs/msg/state.hpp"

#include <franka_semantic_components/franka_robot_model.hpp>
#include <franka_semantic_components/franka_robot_state.hpp>
#include <franka/lowpass_filter.h>

#include <pinocchio/algorithm/kinematics.hpp>
#include <pinocchio/algorithm/frames.hpp>
#include <pinocchio/algorithm/rnea.hpp>
#include <pinocchio/algorithm/crba.hpp>
#include <pinocchio/algorithm/jacobian.hpp>
#include <pinocchio/parsers/urdf.hpp>

// auto-generated by generate_parameter_library
#include "fr3_husky_controller/fr3_controller_parameters.hpp"

#include <fr3_husky_controller/utils/dyros_math.h>
#include <fr3_husky_controller/utils/robot_utils.hpp>

#define FR3_DOF 7

namespace ConsoleColor
{{
    inline constexpr const char* RESET = "\\033[0m";
    inline constexpr const char* BLUE  = "\\033[34m";
    inline constexpr const char* YELLOW= "\\033[33m";
    inline constexpr const char* RED   = "\\033[31m";
}}

#define LOGI(node, fmt, ...) RCLCPP_INFO((node)->get_logger(),  (std::string(ConsoleColor::BLUE)   + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGW(node, fmt, ...) RCLCPP_WARN((node)->get_logger(),  (std::string(ConsoleColor::YELLOW) + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGE(node, fmt, ...) RCLCPP_ERROR((node)->get_logger(), (std::string(ConsoleColor::RED)    + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;
using fr3_controller::ParamListener;
using fr3_controller::Params;

namespace fr3_husky_controller
{{
class {class_name} : public controller_interface::ControllerInterface
{{
    inline static constexpr size_t kPositionIndex = 0;
    inline static constexpr size_t kVelocityIndex = 1;
    inline static constexpr size_t kEffortIndex   = 2;

public:
    // ========================================================================
    // ============================ Core Functions ============================
    // ========================================================================
    [[nodiscard]] controller_interface::InterfaceConfiguration state_interface_configuration() const override;
    [[nodiscard]] controller_interface::InterfaceConfiguration command_interface_configuration() const override;
    CallbackReturn on_init() override;
    CallbackReturn on_configure(const rclcpp_lifecycle::State& previous_state) override;
    CallbackReturn on_activate(const rclcpp_lifecycle::State& previous_state) override;
    CallbackReturn on_deactivate(const rclcpp_lifecycle::State& previous_state) override;
    controller_interface::return_type update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

private:
    // ========================================================================
    // ====================== Main Controller Functions =======================
    // ========================================================================
    void writeCommandInterfaces(const Eigen::VectorXd& command);
    void updateJointStates();
    void updateRobotData();
    void haltCommands();
    void setInitfromCurrent();

    // ========================================================================
    // =========================== Franka robot Data ==========================
    // ========================================================================
    std::vector<std::unique_ptr<franka_semantic_components::FrankaRobotModel>> franka_robot_model_;
    pinocchio::Model pin_model_;
    pinocchio::Data pin_data_;
    bool use_pin_{{false}};

    // Precomputed pinocchio indices/IDs
    std::map<std::string, std::array<int, FR3_DOF>> pin_q_idx_;
    std::map<std::string, std::array<int, FR3_DOF>> pin_v_idx_;
    std::map<std::string, pinocchio::FrameIndex>    pin_link0_id_;
    std::map<std::string, pinocchio::FrameIndex>    pin_ee_id_;
    std::map<std::string, size_t>                   pin_ee_robot_idx_;
    Eigen::VectorXd q_pin_;
    Eigen::VectorXd qdot_pin_;
    Eigen::MatrixXd J_full_;

    // ========================================================================
    // ======================= Manipulator State Data =========================
    // ========================================================================
    std::vector<std::string> robot_names_;

    std::map<std::string, Eigen::Vector<double, FR3_DOF>> q_init_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qdot_init_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qddot_init_;
    Eigen::VectorXd q_total_init_;
    Eigen::VectorXd qdot_total_init_;
    Eigen::VectorXd qddot_total_init_;

    std::map<std::string, Eigen::Vector<double, FR3_DOF>> q_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qdot_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qddot_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> torque_;
    Eigen::VectorXd q_total_;
    Eigen::VectorXd qdot_total_;
    Eigen::VectorXd qddot_total_;
    Eigen::VectorXd torque_total_;

    std::map<std::string, Eigen::Vector<double, FR3_DOF>> q_desired_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qdot_desired_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qddot_desired_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> torque_desired_;
    Eigen::VectorXd q_desired_total_;
    Eigen::VectorXd qdot_desired_total_;
    Eigen::VectorXd qddot_desired_total_;
    Eigen::VectorXd torque_desired_total_;

    // Dynamics
    std::map<std::string, Eigen::Matrix<double, FR3_DOF, FR3_DOF>> M_;
    std::map<std::string, Eigen::Matrix<double, FR3_DOF, FR3_DOF>> M_inv_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> c_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> g_;
    Eigen::MatrixXd M_total_;
    Eigen::MatrixXd M_inv_total_;
    Eigen::VectorXd c_total_;
    Eigen::VectorXd g_total_;

    // ========================================================================
    // ============================= Task Space Data ==========================
    // ========================================================================
    std::vector<std::string> ee_names_;

    std::map<std::string, Eigen::Affine3d> x_init_;
    std::map<std::string, Eigen::Vector6d> xdot_init_;
    std::map<std::string, Eigen::Affine3d> x_;
    std::map<std::string, Eigen::Vector6d> xdot_;
    std::map<std::string, Eigen::Matrix<double, 6, FR3_DOF>> J_;
    std::map<std::string, Eigen::Affine3d> x_desired_;
    std::map<std::string, Eigen::Vector6d> xdot_desired_;

    // ========================================================================
    // =========================== Controller data ============================
    // ========================================================================
    size_t num_robots_{{0}};
    double dt_{{0.0}};
    double play_time_{{0.0}};
    double control_start_time_{{0.0}};
    const std::string arm_id_{{"fr3"}};

    // ========================================================================
    // ============================== Parameters ==============================
    // ========================================================================
    std::shared_ptr<ParamListener> param_listener_;
    Params params_;
    size_t manipulator_dof_{{0}};

    // ========================================================================
    // ============================ Mutex & Thread ============================
    // ========================================================================
    std::mutex robot_data_mutex_;

    // ========================================================================
    // ============================ Interfaces Setup ==========================
    // ========================================================================
    const std::vector<std::string> allowed_interface_types_ = {{
        hardware_interface::HW_IF_POSITION,
        hardware_interface::HW_IF_VELOCITY,
        hardware_interface::HW_IF_EFFORT,
    }};

    struct JointHandle
    {{
        std::vector<std::reference_wrapper<hardware_interface::LoanedStateInterface>> state;
        std::reference_wrapper<hardware_interface::LoanedCommandInterface> command;
        explicit JointHandle(std::reference_wrapper<hardware_interface::LoanedCommandInterface> cmd)
        : command(cmd) {{}}
    }};

    mutable std::vector<JointHandle> registered_manipulator_joint_handles_;

    bool has_position_state_interface_   = false;
    bool has_velocity_state_interface_   = false;
    bool has_effort_state_interface_     = false;
    bool has_position_command_interface_ = false;
    bool has_velocity_command_interface_ = false;
    bool has_effort_command_interface_   = false;

    bool is_halted_       = false;
    bool halt_initialized_ = false;
    std::map<std::string, double> halt_position_;
}};

}}  // namespace fr3_husky_controller
"""


def render_cpp(class_name: str, snake: str) -> str:
    return f"""#include "fr3_husky_controller/{snake}.hpp"

#include <unordered_set>

namespace fr3_husky_controller
{{
controller_interface::InterfaceConfiguration {class_name}::state_interface_configuration() const
{{
    controller_interface::InterfaceConfiguration conf;
    conf.type = controller_interface::interface_configuration_type::INDIVIDUAL;

    for (const auto& joint_name : params_.manipulator_joints)
    {{
        for (const auto& interface_type : params_.manipulator_state_interfaces)
        {{
            conf.names.push_back(joint_name + "/" + interface_type);
        }}
    }}

    if (!use_pin_)
    {{
        for (size_t i = 0; i < num_robots_; ++i)
        {{
            for (const auto& name : franka_robot_model_[i]->get_state_interface_names())
            {{
                conf.names.push_back(name);
            }}
            conf.names.push_back(params_.robot_name[i] + "_" + arm_id_ + "/robot_time");
        }}
    }}

    return conf;
}}

controller_interface::InterfaceConfiguration {class_name}::command_interface_configuration() const
{{
    controller_interface::InterfaceConfiguration conf;
    conf.type = controller_interface::interface_configuration_type::INDIVIDUAL;

    for (const auto& joint_name : params_.manipulator_joints)
    {{
        conf.names.push_back(joint_name + "/" + params_.manipulator_command_interface);
    }}

    return conf;
}}

CallbackReturn {class_name}::on_init()
{{
    try
    {{
        param_listener_ = std::make_shared<ParamListener>(get_node());
        params_ = param_listener_->get_params();
    }}
    catch (const std::exception& e)
    {{
        fprintf(stderr, "Exception thrown during init stage with message: %s\\n", e.what());
        return CallbackReturn::ERROR;
    }}
    return CallbackReturn::SUCCESS;
}}

CallbackReturn {class_name}::on_configure(const rclcpp_lifecycle::State& /*previous_state*/)
{{
    if (param_listener_->is_old(params_))
    {{
        params_ = param_listener_->get_params();
        LOGI(get_node(), "Parameters were updated");
    }}

    num_robots_ = params_.robot_name.size();
    if (num_robots_ < 1 || num_robots_ > 2)
    {{
        LOGE(get_node(), "FR3 controller expects one or two FR3 robots, but got %zu.", num_robots_);
        return CallbackReturn::FAILURE;
    }}

    const std::unordered_set<std::string> allowed = {{"left", "right"}};
    std::unordered_set<std::string> seen;
    for (const auto& name : params_.robot_name)
    {{
        if (allowed.find(name) == allowed.end())
        {{
            LOGE(get_node(), "Invalid robot_name '%s'. Allowed values are 'left' or 'right'.", name.c_str());
            return CallbackReturn::FAILURE;
        }}
        if (!seen.insert(name).second)
        {{
            LOGE(get_node(), "Duplicate robot_name '%s' detected.", name.c_str());
            return CallbackReturn::FAILURE;
        }}
    }}
    robot_names_ = params_.robot_name;

    manipulator_dof_ = params_.manipulator_joints.size();
    if (manipulator_dof_ != FR3_DOF * num_robots_)
    {{
        LOGE(get_node(), "FR3 controller expects %zu manipulator DoF, but got %zu.",
             FR3_DOF * num_robots_, manipulator_dof_);
        return CallbackReturn::FAILURE;
    }}

    has_position_command_interface_ = (params_.manipulator_command_interface == allowed_interface_types_[0]);
    has_velocity_command_interface_ = (params_.manipulator_command_interface == allowed_interface_types_[1]);
    has_effort_command_interface_   = (params_.manipulator_command_interface == allowed_interface_types_[2]);

    has_position_state_interface_ = robot_utils::contains_interface_type(params_.manipulator_state_interfaces, allowed_interface_types_[0]);
    has_velocity_state_interface_ = robot_utils::contains_interface_type(params_.manipulator_state_interfaces, allowed_interface_types_[1]);
    has_effort_state_interface_   = robot_utils::contains_interface_type(params_.manipulator_state_interfaces, allowed_interface_types_[2]);

    if (has_velocity_command_interface_ && (!has_velocity_state_interface_ || !has_position_state_interface_))
    {{
        LOGE(get_node(), "'velocity' command interface requires 'velocity' and 'position' state interfaces.");
        return CallbackReturn::FAILURE;
    }}
    if (has_effort_command_interface_ && (!has_velocity_state_interface_ || !has_position_state_interface_))
    {{
        LOGE(get_node(), "'effort' command interface requires 'velocity' and 'position' state interfaces.");
        return CallbackReturn::FAILURE;
    }}

    if (get_update_rate() == 0)
    {{
        throw std::runtime_error("Controller's update rate is set to 0.");
    }}
    dt_ = 1.0 / static_cast<double>(get_update_rate());

    auto tmp_node = rclcpp::Node::make_shared("_tmp_urdf_client_" + std::string(get_node()->get_name()));
    auto param_client = std::make_shared<rclcpp::SyncParametersClient>(tmp_node, "controller_manager");
    param_client->wait_for_service();
    auto cm_params = param_client->get_parameters({{"robot_description"}});
    std::string urdf_xml = cm_params[0].value_to_string();

    // When using MuJoCo, do not use franka semantic segment
    use_pin_ = (urdf_xml.find("mujoco_ros_hardware/MujocoHardwareInterface") != std::string::npos);
    LOGW(get_node(), "Franka model: %s", !use_pin_ ? "available" : "unavailable (pinocchio fallback)");

    franka_robot_model_.clear();
    if (!use_pin_)
    {{
        for (const auto& name : params_.robot_name)
        {{
            franka_robot_model_.push_back(
                std::make_unique<franka_semantic_components::FrankaRobotModel>(
                    name + "_" + arm_id_ + "/robot_model",
                    name + "_" + arm_id_ + "/robot_state"));
        }}
    }}

    pinocchio::urdf::buildModelFromXML(urdf_xml, pin_model_);
    pin_data_ = pinocchio::Data(pin_model_);

    for (const auto& robot_name : robot_names_)
    {{
        q_init_[robot_name]     = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        qdot_init_[robot_name]  = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        qddot_init_[robot_name] = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        q_[robot_name]      = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        qdot_[robot_name]   = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        qddot_[robot_name]  = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        torque_[robot_name] = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        q_desired_[robot_name]      = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        qdot_desired_[robot_name]   = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        qddot_desired_[robot_name]  = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        torque_desired_[robot_name] = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        M_[robot_name] = Eigen::Matrix<double, FR3_DOF, FR3_DOF>::Zero();
        M_inv_[robot_name] = Eigen::Matrix<double, FR3_DOF, FR3_DOF>::Zero();
        c_[robot_name] = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
        g_[robot_name] = Eigen::Matrix<double, FR3_DOF, 1>::Zero();
    }}

    q_total_init_.setZero(manipulator_dof_);
    qdot_total_init_.setZero(manipulator_dof_);
    qddot_total_init_.setZero(manipulator_dof_);
    q_total_.setZero(manipulator_dof_);
    qdot_total_.setZero(manipulator_dof_);
    qddot_total_.setZero(manipulator_dof_);
    torque_total_.setZero(manipulator_dof_);
    q_desired_total_.setZero(manipulator_dof_);
    qdot_desired_total_.setZero(manipulator_dof_);
    qddot_desired_total_.setZero(manipulator_dof_);
    torque_desired_total_.setZero(manipulator_dof_);
    M_total_.setZero(manipulator_dof_, manipulator_dof_);
    M_inv_total_.setZero(manipulator_dof_, manipulator_dof_);
    c_total_.setZero(manipulator_dof_);
    g_total_.setZero(manipulator_dof_);

    ee_names_.clear();
    for (const auto& name : params_.robot_name)
    {{
        const std::string hand_tcp = name + "_" + arm_id_ + "_hand_tcp";
        const std::string link8    = name + "_" + arm_id_ + "_link8";
        const bool has_hand = pin_model_.getFrameId(hand_tcp) < static_cast<pinocchio::FrameIndex>(pin_model_.nframes);
        ee_names_.push_back(has_hand ? hand_tcp : link8);
    }}

    q_pin_    = Eigen::VectorXd::Zero(pin_model_.nq);
    qdot_pin_ = Eigen::VectorXd::Zero(pin_model_.nv);
    J_full_   = Eigen::MatrixXd::Zero(6, pin_model_.nv);
    for (size_t i = 0; i < robot_names_.size(); ++i)
    {{
        const std::string& rn = robot_names_[i];
        for (int j = 0; j < FR3_DOF; ++j)
        {{
            const std::string jname = rn + "_" + arm_id_ + "_joint" + std::to_string(j + 1);
            const pinocchio::JointIndex jid = pin_model_.getJointId(jname);
            pin_q_idx_[rn][j] = pin_model_.joints[jid].idx_q();
            pin_v_idx_[rn][j] = pin_model_.joints[jid].idx_v();
        }}
        pin_link0_id_[rn] = pin_model_.getFrameId(rn + "_" + arm_id_ + "_link0");
    }}
    for (size_t i = 0; i < ee_names_.size(); ++i)
    {{
        pin_ee_id_[ee_names_[i]]        = pin_model_.getFrameId(ee_names_[i]);
        pin_ee_robot_idx_[ee_names_[i]] = i;
    }}

    for (const auto& ee_name : ee_names_)
    {{
        x_init_[ee_name]     = Eigen::Affine3d::Identity();
        xdot_init_[ee_name]  = Eigen::Vector6d::Zero();
        x_[ee_name]          = Eigen::Affine3d::Identity();
        xdot_[ee_name]       = Eigen::Vector6d::Zero();
        J_[ee_name]          = Eigen::Matrix<double, 6, FR3_DOF>::Zero();
        x_desired_[ee_name]  = Eigen::Affine3d::Identity();
        xdot_desired_[ee_name] = Eigen::Vector6d::Zero();
    }}

    return CallbackReturn::SUCCESS;
}}

CallbackReturn {class_name}::on_activate(const rclcpp_lifecycle::State& /*previous_state*/)
{{
    std::vector<std::vector<std::reference_wrapper<hardware_interface::LoanedStateInterface>>> state_by_type(
        allowed_interface_types_.size());
    std::vector<std::reference_wrapper<hardware_interface::LoanedCommandInterface>> cmd_by_type;

    for (const auto& interface : params_.manipulator_state_interfaces)
    {{
        auto it = std::find(allowed_interface_types_.begin(), allowed_interface_types_.end(), interface);
        if (it == allowed_interface_types_.end()) continue;
        size_t idx = static_cast<size_t>(std::distance(allowed_interface_types_.begin(), it));
        if (!controller_interface::get_ordered_interfaces(
                state_interfaces_, params_.manipulator_joints, interface, state_by_type[idx]))
        {{
            LOGE(get_node(), "Expected %zu '%s' state interfaces, got %zu.",
                 manipulator_dof_, interface.c_str(), state_by_type[idx].size());
            return CallbackReturn::ERROR;
        }}
    }}

    const auto& cmd_interface = params_.manipulator_command_interface;
    auto it = std::find(allowed_interface_types_.begin(), allowed_interface_types_.end(), cmd_interface);
    if (it == allowed_interface_types_.end())
    {{
        LOGE(get_node(), "Invalid command_interface '%s'.", cmd_interface.c_str());
        return CallbackReturn::ERROR;
    }}
    if (!controller_interface::get_ordered_interfaces(
            command_interfaces_, params_.manipulator_joints, cmd_interface, cmd_by_type))
    {{
        LOGE(get_node(), "Expected %zu '%s' command interfaces, got %zu.",
             manipulator_dof_, cmd_interface.c_str(), cmd_by_type.size());
        return CallbackReturn::ERROR;
    }}

    registered_manipulator_joint_handles_.clear();
    for (size_t i = 0; i < manipulator_dof_; ++i)
    {{
        registered_manipulator_joint_handles_.emplace_back(cmd_by_type[i]);
        auto& handle = registered_manipulator_joint_handles_.back();
        handle.state.clear();

        auto default_state_ref = state_by_type[kPositionIndex][i];
        handle.state.assign(allowed_interface_types_.size(), default_state_ref);

        if (has_position_state_interface_) handle.state[kPositionIndex] = state_by_type[kPositionIndex][i];
        if (has_velocity_state_interface_) handle.state[kVelocityIndex] = state_by_type[kVelocityIndex][i];
        if (has_effort_state_interface_ && !state_by_type[kEffortIndex].empty())
            handle.state[kEffortIndex] = state_by_type[kEffortIndex][i];
    }}

    if (!use_pin_)
    {{
        try
        {{
            for (const auto& model : franka_robot_model_)
            {{
                model->assign_loaned_state_interfaces(state_interfaces_);
            }}
        }}
        catch (const std::exception& e)
        {{
            LOGW(get_node(), "Franka semantic component state interfaces not available (%s). Falling back to pinocchio.", e.what());
            use_pin_ = true;
        }}
    }}

    is_halted_ = false;
    updateJointStates();
    updateRobotData();
    setInitfromCurrent();

    return CallbackReturn::SUCCESS;
}}

controller_interface::CallbackReturn {class_name}::on_deactivate(const rclcpp_lifecycle::State& /*previous_state*/)
{{
    if (!is_halted_)
    {{
        haltCommands();
        is_halted_ = true;
    }}
    halt_initialized_ = false;
    registered_manipulator_joint_handles_.clear();
    return CallbackReturn::SUCCESS;
}}

controller_interface::return_type {class_name}::update(const rclcpp::Time& /*time*/, const rclcpp::Duration& /*period*/)
{{
    if (get_state().id() == lifecycle_msgs::msg::State::PRIMARY_STATE_INACTIVE)
    {{
        if (!is_halted_)
        {{
            haltCommands();
            is_halted_ = true;
        }}
        return controller_interface::return_type::OK;
    }}

    updateJointStates();
    updateRobotData();

    // -------------------------------------------------------------------------
    // TODO: implement your own controller algorithm
    // -------------------------------------------------------------------------

    if (has_position_command_interface_)
    {{
        for (size_t i = 0; i < num_robots_; ++i)
        {{
            q_desired_[robot_names_[i]] = q_init_[robot_names_[i]];
            q_desired_total_.segment(i * FR3_DOF, FR3_DOF) = q_desired_[robot_names_[i]];
        }}
        writeCommandInterfaces(q_desired_total_);
    }}
    else if (has_velocity_command_interface_)
    {{
        for (size_t i = 0; i < num_robots_; ++i)
        {{
            qdot_desired_[robot_names_[i]].setZero();
            qdot_desired_total_.segment(i * FR3_DOF, FR3_DOF) = qdot_desired_[robot_names_[i]];
        }}
        writeCommandInterfaces(qdot_desired_total_);
    }}
    else
    {{
        for (size_t i = 0; i < num_robots_; ++i)
        {{
            torque_desired_[robot_names_[i]].setZero();
            torque_desired_total_.segment(i * FR3_DOF, FR3_DOF) = torque_desired_[robot_names_[i]];
        }}
        writeCommandInterfaces(torque_desired_total_);
    }}

    // -------------------------------------------------------------------------

    return controller_interface::return_type::OK;
}}

void {class_name}::haltCommands()
{{
    if (registered_manipulator_joint_handles_.empty()) return;

    if (!halt_initialized_)
    {{
        halt_position_.clear();
        for (size_t i = 0; i < registered_manipulator_joint_handles_.size(); ++i)
        {{
            const std::string jname = registered_manipulator_joint_handles_[i].command.get().get_name();
            if (jname.find(arm_id_) != std::string::npos && jname.find("joint") != std::string::npos)
            {{
                halt_position_[jname] = registered_manipulator_joint_handles_[i].state[kPositionIndex].get().get_value();
            }}
        }}
        halt_initialized_ = true;
    }}

    if (has_position_command_interface_)
    {{
        for (size_t i = 0; i < registered_manipulator_joint_handles_.size(); ++i)
        {{
            const std::string jname = registered_manipulator_joint_handles_[i].command.get().get_name();
            auto it = halt_position_.find(jname);
            if (it != halt_position_.end())
                registered_manipulator_joint_handles_[i].command.get().set_value(it->second);
        }}
    }}
    else if (has_velocity_command_interface_)
    {{
        for (auto& h : registered_manipulator_joint_handles_) h.command.get().set_value(0.0);
    }}
    else  // effort
    {{
        const Eigen::Vector<double, FR3_DOF> kp{{600.0, 600.0, 600.0, 600.0, 250.0, 150.0, 50.0}};
        const Eigen::Vector<double, FR3_DOF> kv{{ 30.0,  30.0,  30.0,  30.0,  10.0,  10.0,  5.0}};

        for (size_t i = 0; i < registered_manipulator_joint_handles_.size(); ++i)
        {{
            const std::string jname = registered_manipulator_joint_handles_[i].command.get().get_name();
            auto it = halt_position_.find(jname);
            if (it == halt_position_.end()) continue;

            int joint_idx = -1;
            for (int j = 1; j <= static_cast<int>(FR3_DOF); ++j)
            {{
                if (jname.find(std::to_string(j)) != std::string::npos)
                    joint_idx = j - 1;
            }}
            if (joint_idx < 0)
            {{
                registered_manipulator_joint_handles_[i].command.get().set_value(0.0);
                continue;
            }}
            const double q_halted  = it->second;
            const double q_curr    = registered_manipulator_joint_handles_[i].state[kPositionIndex].get().get_value();
            const double qdot_curr = has_velocity_state_interface_
                ? registered_manipulator_joint_handles_[i].state[kVelocityIndex].get().get_value() : 0.0;
            registered_manipulator_joint_handles_[i].command.get().set_value(
                kp[joint_idx] * (q_halted - q_curr) - kv[joint_idx] * qdot_curr);
        }}
    }}
}}

void {class_name}::writeCommandInterfaces(const Eigen::VectorXd& command)
{{
    if (static_cast<size_t>(command.size()) == manipulator_dof_)
    {{
        for (size_t i = 0; i < registered_manipulator_joint_handles_.size(); ++i)
            registered_manipulator_joint_handles_[i].command.get().set_value(command(i));
    }}
    else
    {{
        LOGW(get_node(), "Command size mismatch (expected %zu, got %zu). Holding.", manipulator_dof_, command.size());
        if (has_position_command_interface_)
        {{
            for (size_t i = 0; i < registered_manipulator_joint_handles_.size(); ++i)
            {{
                const double cur = registered_manipulator_joint_handles_[i].state[kPositionIndex].get().get_value();
                registered_manipulator_joint_handles_[i].command.get().set_value(cur);
            }}
        }}
        else
        {{
            for (auto& h : registered_manipulator_joint_handles_) h.command.get().set_value(0.0);
        }}
    }}
}}

void {class_name}::updateJointStates()
{{
    const Eigen::VectorXd last_qdot_total = qdot_total_;
    for (size_t i = 0; i < manipulator_dof_; ++i)
    {{
        if (has_position_state_interface_) q_total_(i)      = registered_manipulator_joint_handles_[i].state[kPositionIndex].get().get_value();
        if (has_velocity_state_interface_) qdot_total_(i)   = registered_manipulator_joint_handles_[i].state[kVelocityIndex].get().get_value();
        if (has_effort_state_interface_)   torque_total_(i) = registered_manipulator_joint_handles_[i].state[kEffortIndex].get().get_value();
    }}

    qddot_total_ = (qdot_total_ - last_qdot_total) / dt_;

    for (size_t r = 0; r < num_robots_; ++r)
    {{
        const std::string& robot_name = robot_names_[r];
        q_[robot_name]      = q_total_.segment(FR3_DOF * r, FR3_DOF);
        qdot_[robot_name]   = qdot_total_.segment(FR3_DOF * r, FR3_DOF);
        qddot_[robot_name]  = qddot_total_.segment(FR3_DOF * r, FR3_DOF);
        torque_[robot_name] = torque_total_.segment(FR3_DOF * r, FR3_DOF);
    }}
}}

void {class_name}::updateRobotData()
{{
    play_time_ = get_node()->now().seconds();

    if (use_pin_)
    {{
        q_pin_.setZero();
        qdot_pin_.setZero();
        for (size_t i = 0; i < num_robots_; ++i)
        {{
            const std::string& rn    = robot_names_[i];
            const auto& q_idx = pin_q_idx_.at(rn);
            const auto& v_idx = pin_v_idx_.at(rn);
            for (int j = 0; j < FR3_DOF; ++j)
            {{
                q_pin_(q_idx[j])    = q_[rn](j);
                qdot_pin_(v_idx[j]) = qdot_[rn](j);
            }}
        }}

        pinocchio::forwardKinematics(pin_model_, pin_data_, q_pin_, qdot_pin_);
        pinocchio::updateFramePlacements(pin_model_, pin_data_);
        pinocchio::computeJointJacobians(pin_model_, pin_data_, q_pin_);
        pinocchio::crba(pin_model_, pin_data_, q_pin_);
        pin_data_.M.triangularView<Eigen::StrictlyLower>() =
            pin_data_.M.transpose().triangularView<Eigen::StrictlyLower>();
        pinocchio::computeGeneralizedGravity(pin_model_, pin_data_, q_pin_);
        pinocchio::nonLinearEffects(pin_model_, pin_data_, q_pin_, qdot_pin_);

        for (size_t i = 0; i < num_robots_; ++i)
        {{
            const std::string& robot_name = robot_names_[i];
            const auto& v_idx = pin_v_idx_.at(robot_name);

            Eigen::Matrix<double, FR3_DOF, FR3_DOF> M_i;
            Eigen::Matrix<double, FR3_DOF, 1> g_i, c_i;
            for (int a = 0; a < FR3_DOF; ++a)
            {{
                g_i(a) = pin_data_.g(v_idx[a]);
                c_i(a) = pin_data_.nle(v_idx[a]) - pin_data_.g(v_idx[a]);
                for (int b = 0; b < FR3_DOF; ++b)
                    M_i(a, b) = pin_data_.M(v_idx[a], v_idx[b]);
            }}
            {{
                std::lock_guard<std::mutex> lock(robot_data_mutex_);
                M_[robot_name]     = M_i;
                M_inv_[robot_name] = M_i.inverse();
                g_[robot_name]     = g_i;
                c_[robot_name]     = c_i;
                M_total_.block(FR3_DOF * i, FR3_DOF * i, FR3_DOF, FR3_DOF)     = M_i;
                M_inv_total_.block(FR3_DOF * i, FR3_DOF * i, FR3_DOF, FR3_DOF) = M_i.inverse();
                g_total_.segment(FR3_DOF * i, FR3_DOF) = g_i;
                c_total_.segment(FR3_DOF * i, FR3_DOF) = c_i;
            }}
        }}

        for (const auto& ee_name : ee_names_)
        {{
            const size_t       i          = pin_ee_robot_idx_.at(ee_name);
            const std::string& robot_name = robot_names_[i];
            const auto&        v_idx      = pin_v_idx_.at(robot_name);
            const pinocchio::FrameIndex ee_id    = pin_ee_id_.at(ee_name);
            const pinocchio::FrameIndex link0_id = pin_link0_id_.at(robot_name);

            const pinocchio::SE3& T_w_ee    = pin_data_.oMf[ee_id];
            const pinocchio::SE3& T_w_link0 = pin_data_.oMf[link0_id];
            const pinocchio::SE3  T_link0_ee = T_w_link0.actInv(T_w_ee);

            J_full_.setZero();
            pinocchio::getFrameJacobian(pin_model_, pin_data_, ee_id,
                pinocchio::ReferenceFrame::LOCAL_WORLD_ALIGNED, J_full_);

            const Eigen::Matrix3d R = T_w_link0.rotation().transpose();
            Eigen::Matrix<double, 6, FR3_DOF> J_link0;
            for (int j = 0; j < FR3_DOF; ++j)
                J_link0.col(j) = J_full_.col(v_idx[j]);
            J_link0.topRows(3)    = R * J_link0.topRows(3);
            J_link0.bottomRows(3) = R * J_link0.bottomRows(3);

            {{
                std::lock_guard<std::mutex> lock(robot_data_mutex_);
                x_[ee_name].matrix() = T_link0_ee.toHomogeneousMatrix();
                J_[ee_name]            = J_link0;
                xdot_[ee_name]       = J_link0 * qdot_[robot_name];
            }}
        }}
    }}
    else
    {{
        M_total_.setZero(manipulator_dof_, manipulator_dof_);
        for (size_t i = 0; i < num_robots_; ++i)
        {{
            const std::string& robot_name = robot_names_[i];
            std::array<double, FR3_DOF * FR3_DOF> mass     = franka_robot_model_[i]->getMassMatrix();
            std::array<double, FR3_DOF>            coriolis = franka_robot_model_[i]->getCoriolisForceVector();
            std::array<double, FR3_DOF>            gravity  = franka_robot_model_[i]->getGravityForceVector();
            {{
                std::lock_guard<std::mutex> lock(robot_data_mutex_);
                M_[robot_name]     = Eigen::Map<const Eigen::Matrix<double, FR3_DOF, FR3_DOF, Eigen::RowMajor>>(mass.data());
                g_[robot_name]     = Eigen::Map<const Eigen::Matrix<double, FR3_DOF, 1>>(gravity.data());
                c_[robot_name]     = Eigen::Map<const Eigen::Matrix<double, FR3_DOF, 1>>(coriolis.data());
                M_inv_[robot_name] = M_[robot_name].inverse();
                M_total_.block(FR3_DOF * i, FR3_DOF * i, FR3_DOF, FR3_DOF) = M_[robot_name];
                M_inv_total_.block(FR3_DOF * i, FR3_DOF * i, FR3_DOF, FR3_DOF) = M_inv_[robot_name];
                g_total_.segment(FR3_DOF * i, FR3_DOF) = g_[robot_name];
                c_total_.segment(FR3_DOF * i, FR3_DOF) = c_[robot_name];
            }}
        }}

        for (const auto& ee_name : ee_names_)
        {{
            for (size_t i = 0; i < num_robots_; ++i)
            {{
                if (ee_name.find(robot_names_[i]) != std::string::npos)
                {{
                    std::array<double, 16> pose = franka_robot_model_[i]->getPoseMatrix(franka::Frame::kEndEffector);
                    std::array<double, 42> jac  = franka_robot_model_[i]->getZeroJacobian(franka::Frame::kEndEffector);
                    x_[ee_name].matrix() = Eigen::Map<const Eigen::Matrix4d>(pose.data());
                    J_[ee_name] = Eigen::Map<const Eigen::Matrix<double, 6, FR3_DOF, Eigen::ColMajor>>(jac.data());
                    xdot_[ee_name] = J_[ee_name] * qdot_[robot_names_[i]];
                    break;
                }}
            }}
        }}
    }}
}}

void {class_name}::setInitfromCurrent()
{{
    q_init_    = q_;
    qdot_init_ = qdot_;
    qddot_init_ = qdot_;
    q_total_init_    = q_total_;
    qdot_total_init_ = qdot_total_;
    qddot_total_init_ = qdot_total_;
    x_init_    = x_;
    xdot_init_ = xdot_;
    control_start_time_ = play_time_;
}}

}}  // namespace fr3_husky_controller
#include "pluginlib/class_list_macros.hpp"
// NOLINTNEXTLINE
PLUGINLIB_EXPORT_CLASS(fr3_husky_controller::{class_name}, controller_interface::ControllerInterface)
"""


# ---------------------------------------------------------------------------
# CMakeLists patcher
# ---------------------------------------------------------------------------

def patch_cmakelists(cmake_path: Path, new_cpp_rel: str) -> Tuple[bool, str]:
    """Add new_cpp_rel to the add_library block. Deduped."""
    text = cmake_path.read_text(encoding="utf-8")
    if new_cpp_rel in text:
        return False, f"Already present: {new_cpp_rel}"

    lines = text.splitlines(True)

    def find_blocks():
        blocks = []
        i = 0
        while i < len(lines):
            if re.match(r"^\s*add_(library|executable)\s*\(", lines[i]):
                start = i
                depth = lines[i].count("(") - lines[i].count(")")
                i += 1
                while i < len(lines) and depth > 0:
                    depth += lines[i].count("(") - lines[i].count(")")
                    i += 1
                blocks.append((start, i))
            else:
                i += 1
        return blocks

    blocks = find_blocks()

    # Pick the add_library block containing ${PROJECT_NAME}; fall back to first block
    chosen = None
    for s, e in blocks:
        if "${PROJECT_NAME}" in "".join(lines[s:e]):
            chosen = (s, e)
            break
    if chosen is None and blocks:
        chosen = blocks[0]

    if chosen is None:
        hint = f"\n# TODO: add {new_cpp_rel} to your add_library target\n"
        cmake_path.write_text(text + hint, encoding="utf-8")
        return True, "No add_library block found; appended hint."

    s, e = chosen

    # Find last closing paren line
    insert_at = None
    for j in range(e - 1, s - 1, -1):
        if ")" in lines[j]:
            insert_at = j
            break
    if insert_at is None:
        insert_at = e

    # Detect indent from existing src/ lines
    indent = "  "
    for j in range(s, e):
        if "src/" in lines[j]:
            m = re.match(r"^(\s+)\S", lines[j])
            if m:
                indent = m.group(1)
                break

    lines.insert(insert_at, f"{indent}{new_cpp_rel}\n")
    cmake_path.write_text("".join(lines), encoding="utf-8")
    return True, f"Inserted into add_library: {new_cpp_rel}"


# ---------------------------------------------------------------------------
# Plugin XML patcher
# ---------------------------------------------------------------------------

def patch_plugin_xml(xml_path: Path, class_name: str) -> Tuple[bool, str]:
    """Add a <class> entry for class_name. Deduped."""
    text = xml_path.read_text(encoding="utf-8")
    full_class = f"fr3_husky_controller/{class_name}"

    if full_class in text:
        return False, f"Already present: {full_class}"

    new_entry = (
        f'\n  <class name="fr3_husky_controller/{class_name}"\n'
        f'         type="fr3_husky_controller::{class_name}"\n'
        f'         base_class_type="controller_interface::ControllerInterface">\n'
        f'    <description>\n'
        f'      {class_name} controller.\n'
        f'    </description>\n'
        f'  </class>\n'
    )

    # Insert before </library>
    insertion_point = text.rfind("</library>")
    if insertion_point == -1:
        xml_path.write_text(text + new_entry, encoding="utf-8")
        return True, "No </library> tag found; appended entry."

    updated = text[:insertion_point] + new_entry + text[insertion_point:]
    xml_path.write_text(updated, encoding="utf-8")
    return True, f"Inserted class entry for {full_class}"


# ---------------------------------------------------------------------------
# YAML patcher
# ---------------------------------------------------------------------------

SINGLE_ARM_JOINTS_TEMPLATE = """\
        - {side}_fr3_joint1
        - {side}_fr3_joint2
        - {side}_fr3_joint3
        - {side}_fr3_joint4
        - {side}_fr3_joint5
        - {side}_fr3_joint6
        - {side}_fr3_joint7"""

DUAL_ARM_JOINTS_TEMPLATE = """\
        - left_fr3_joint1
        - left_fr3_joint2
        - left_fr3_joint3
        - left_fr3_joint4
        - left_fr3_joint5
        - left_fr3_joint6
        - left_fr3_joint7
        - right_fr3_joint1
        - right_fr3_joint2
        - right_fr3_joint3
        - right_fr3_joint4
        - right_fr3_joint5
        - right_fr3_joint6
        - right_fr3_joint7"""

STATE_INTERFACES_FOR_MODE = {
    "position": "        - position\n        - velocity",
    "velocity": "        - position\n        - velocity",
    "effort":   "        - position\n        - velocity\n        - effort",
}


def make_yaml_type_block(ctrl_name: str, class_name: str) -> str:
    return (
        f"\n      {ctrl_name}:\n"
        f"        type: fr3_husky_controller/{class_name}\n"
    )


def make_yaml_param_block(ctrl_name: str, robot_names: list, joints_str: str, control_mode: str) -> str:
    robot_names_str = '["' + '", "'.join(robot_names) + '"]'
    state_ifaces = STATE_INTERFACES_FOR_MODE.get(control_mode, STATE_INTERFACES_FOR_MODE["effort"])
    return (
        f"\n  {ctrl_name}:\n"
        f"    ros__parameters:\n"
        f"      update_rate: 1000  # Hz\n"
        f"      robot_name: {robot_names_str}\n"
        f"      manipulator_joints:\n"
        f"{joints_str}\n"
        f"      manipulator_state_interfaces:\n"
        f"{state_ifaces}\n"
        f"      manipulator_command_interface: {control_mode}\n"
    )


def patch_yaml(yaml_path: Path, snake: str, class_name: str, control_mode: str) -> Tuple[bool, str]:
    """
    1. Add type declarations under controller_manager/ros__parameters.
    2. Append left/right/dual parameter sections at the end.
    """
    text = yaml_path.read_text(encoding="utf-8")

    left_name  = f"left_{snake}"
    right_name = f"right_{snake}"
    dual_name  = f"dual_{snake}"

    if left_name in text:
        return False, f"Already present: {left_name}"

    # --- Part 1: insert type declarations ---
    # Type lines inside controller_manager are indented 8 spaces:
    #   "        type: fr3_husky_controller/..."
    # Find the last such line and append our entries after it.
    type_pattern = re.compile(r"^ {8}type: fr3_husky_controller/\S+", re.MULTILINE)
    matches = list(type_pattern.finditer(text))

    new_type_entries = (
        f"\n\n      {left_name}:\n        type: fr3_husky_controller/{class_name}"
        f"\n\n      {right_name}:\n        type: fr3_husky_controller/{class_name}"
        f"\n\n      {dual_name}:\n        type: fr3_husky_controller/{class_name}"
    )

    if matches:
        last_match = matches[-1]
        # Advance to end of the line
        line_end = text.find("\n", last_match.end())
        if line_end == -1:
            line_end = len(text)
        else:
            line_end += 1  # include the newline
        text = text[:line_end] + new_type_entries + "\n" + text[line_end:]
    else:
        # Fallback: append after controller_manager/ros__parameters: line
        cm_pattern = re.search(r"ros__parameters:\n", text)
        if cm_pattern:
            insert_pos = cm_pattern.end()
            text = text[:insert_pos] + new_type_entries + "\n" + text[insert_pos:]
        else:
            text += "\n" + new_type_entries + "\n"

    # --- Part 2: append parameter sections ---
    left_joints  = SINGLE_ARM_JOINTS_TEMPLATE.format(side="left")
    right_joints = SINGLE_ARM_JOINTS_TEMPLATE.format(side="right")
    dual_joints  = DUAL_ARM_JOINTS_TEMPLATE

    left_block  = make_yaml_param_block(left_name,  ["left"],          left_joints,  control_mode)
    right_block = make_yaml_param_block(right_name, ["right"],         right_joints, control_mode)
    dual_block  = make_yaml_param_block(dual_name,  ["left", "right"], dual_joints,  control_mode)

    text = text.rstrip("\n") + "\n" + left_block + right_block + dual_block

    yaml_path.write_text(text, encoding="utf-8")
    return True, f"Added left/right/dual entries for {snake}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate FR3 controller boilerplate."
    )
    ap.add_argument("name", help="Server name (any style). Used for file/class names.")
    ap.add_argument(
        "--control_mode",
        type=str,
        required=True,
        choices=["position", "velocity", "effort"],
        help="Control Mode [position, velocity, effort]",
    )
    ap.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files.",
    )
    args = ap.parse_args()

    pkg_root  = script_pkg_root()
    cmake_path = pkg_root / "CMakeLists.txt"
    xml_path   = pkg_root / "fr3_husky_plugin.xml"
    yaml_path  = pkg_root / "config" / "fr3_ros_controllers.yaml"

    for path in (cmake_path, xml_path, yaml_path):
        if not path.exists():
            raise FileNotFoundError(f"Required file not found: {path}")

    snake      = to_snake(args.name)
    class_name = to_camel(snake)

    hpp_path = pkg_root / "include" / "fr3_husky_controller" / f"{snake}.hpp"
    cpp_path = pkg_root / "src" / f"{snake}.cpp"

    if (hpp_path.exists() or cpp_path.exists()) and not args.force:
        raise FileExistsError(
            f"Target file(s) exist:\n  {hpp_path}\n  {cpp_path}\nUse --force to overwrite."
        )

    ensure_dir(hpp_path.parent)
    ensure_dir(cpp_path.parent)

    hpp_path.write_text(render_hpp(class_name), encoding="utf-8")
    cpp_path.write_text(render_cpp(class_name, snake), encoding="utf-8")

    cmake_changed, cmake_msg   = patch_cmakelists(cmake_path, f"src/{snake}.cpp")
    xml_changed,   xml_msg     = patch_plugin_xml(xml_path, class_name)
    yaml_changed,  yaml_msg    = patch_yaml(yaml_path, snake, class_name, args.control_mode)

    print("Generated:")
    print(f"  - {hpp_path.relative_to(pkg_root)}")
    print(f"  - {cpp_path.relative_to(pkg_root)}")
    print("CMakeLists.txt:")
    print(f"  - {cmake_msg}")
    print("fr3_husky_plugin.xml:")
    print(f"  - {xml_msg}")
    print("config/fr3_ros_controllers.yaml:")
    print(f"  - {yaml_msg}")

    print(f"\nController class : fr3_husky_controller::{class_name}")
    print(f"Plugin type      : fr3_husky_controller/{class_name}")
    print(f"YAML controllers : left_{snake}, right_{snake}, dual_{snake}")
    print(f"Control mode     : {args.control_mode}")
    print("\nNext steps:")
    print("  1) Fill the TODO in update() with your control algorithm")
    print("  2) Build: colcon build --packages-select fr3_husky_controller")


if __name__ == "__main__":
    main()
