#pragma once

#include <string>
#include <chrono>
#include <array>
#include <memory>
#include <mutex>
#include <cassert>
#include <cmath>
#include <exception>
#include <map>
#include <functional>
#include <vector>
#include <algorithm>
#include <numeric>
#include <sstream>
#include <type_traits>
#include <Eigen/Eigen>

#if __cplusplus < 201703L
// Fallback for toolchains/IntelliSense not using C++17.
namespace std {
template <class From, class To>
constexpr bool is_convertible_v = std::is_convertible<From, To>::value;
}  // namespace std
#endif

#include <rclcpp/rclcpp.hpp>
#include <ament_index_cpp/get_package_share_directory.hpp>
#include <controller_interface/controller_interface.hpp>
#include <controller_interface/helpers.hpp>
#include <hardware_interface/loaned_command_interface.hpp>
#include <hardware_interface/types/hardware_interface_type_values.hpp>
#include <rclcpp_action/create_server.hpp>
#include <rclcpp_action/server_goal_handle.hpp>
#include <rclcpp_lifecycle/state.hpp>
#include <geometry_msgs/msg/pose_stamped.hpp>
#include "lifecycle_msgs/msg/state.hpp"

#include <franka_semantic_components/franka_robot_model.hpp>
#include <franka_semantic_components/franka_robot_state.hpp>
#include <franka/lowpass_filter.h>

// auto-generated by generate_parameter_library
#include "fr3_husky_controller/fr3_action_controller_parameters.hpp"

#include <fr3_husky_controller/utils/dyros_math.h>
#include <fr3_husky_controller/utils/robot_utils.hpp>
#include <fr3_husky_controller/model/fr3_model_updater.hpp>

#include "dyros_robot_controller/manipulator/robot_data.h"
#include "dyros_robot_controller/manipulator/robot_controller.h"

#include <fr3_husky_controller/servers/action_server_base.hpp>
#include <fr3_husky_controller/servers/idle_control.hpp>

namespace ConsoleColor 
{
    inline constexpr const char* RESET = "\033[0m";
    inline constexpr const char* BLUE  = "\033[34m"; // Info
    inline constexpr const char* YELLOW= "\033[33m"; // Warn
    inline constexpr const char* RED   = "\033[31m"; // Error
}

#define LOGI(node, fmt, ...) RCLCPP_INFO((node)->get_logger(),  (std::string(ConsoleColor::BLUE)   + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGW(node, fmt, ...) RCLCPP_WARN((node)->get_logger(),  (std::string(ConsoleColor::YELLOW) + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGE(node, fmt, ...) RCLCPP_ERROR((node)->get_logger(), (std::string(ConsoleColor::RED)    + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;
using fr3_action_controller::ParamListener;
using fr3_action_controller::Params;

namespace fr3_husky_controller 
{
class FR3ActionController : public controller_interface::ControllerInterface 
{
    // Shared interface slot indices
    inline static constexpr size_t kPositionIndex = 0;
    inline static constexpr size_t kVelocityIndex = 1;
    inline static constexpr size_t kEffortIndex   = 2;

    public:
        // ========================================================================
        // ============================ Core Functions ============================
        // ========================================================================
        [[nodiscard]] controller_interface::InterfaceConfiguration state_interface_configuration() const override;
        [[nodiscard]] controller_interface::InterfaceConfiguration command_interface_configuration() const override;
        CallbackReturn on_init() override;
        CallbackReturn on_configure(const rclcpp_lifecycle::State& previous_state) override;
        CallbackReturn on_activate(const rclcpp_lifecycle::State& previous_state) override;
        CallbackReturn on_deactivate(const rclcpp_lifecycle::State& previous_state) override;
        controller_interface::return_type update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

    private:
        // ========================================================================
        // =========================== Franka robot Data ==========================
        // ========================================================================
        std::vector<std::unique_ptr<franka_semantic_components::FrankaRobotModel>> franka_robot_model_;
        bool use_franka_model_{false};
        
        // ========================================================================
        // ============================= Task Space Data ==========================
        // ========================================================================
        std::vector<std::string> ee_names_;

        // ========================================================================
        // =========================== Controller data ============================
        // ========================================================================
        size_t num_robots_{0}; // number of FR3 arms
        double dt_{0.0};
        double play_time_{0.0};
        double control_start_time_{0.0};

        const std::string arm_id_{"fr3"};

        // ========================================================================
        // ============================== Parameters ==============================
        // ========================================================================
        std::shared_ptr<ParamListener> param_listener_;
        Params params_;
        size_t manipulator_dof_{0};

        // ========================================================================
        // ============================ Interfaces Setup ==========================
        // ========================================================================
        // Interface ordering (keeps indices consistent across interface types).
        const std::vector<std::string> allowed_interface_types_ = {
            hardware_interface::HW_IF_POSITION,
            hardware_interface::HW_IF_VELOCITY,
            hardware_interface::HW_IF_EFFORT,
        };
        
        bool has_position_state_interface_ = false;
        bool has_velocity_state_interface_ = false;
        bool has_effort_state_interface_ = false;
        bool has_position_command_interface_ = false;
        bool has_velocity_command_interface_ = false;
        bool has_effort_command_interface_ = false;

        bool is_halted_ = false;

        // ========================================================================
        // ============================ Action Servers ============================
        // ========================================================================
        std::unique_ptr<FR3ModelUpdater> model_updater_;
        bool loadDRCGains(std::shared_ptr<drc::Manipulator::RobotController> robot_controller);
        std::vector<std::shared_ptr<fr3_husky_controller::servers::ActionServerManager>> action_servers_;
        std::shared_ptr<fr3_husky_controller::servers::ActionServerManager> active_server_;
        std::unique_ptr<fr3_husky_controller::servers::IdleControl> idle_control_;

};

}  // namespace fr3_husky_controller
