#pragma once

#include <string>
#include <chrono>
#include <array>
#include <memory>
#include <mutex>
#include <cassert>
#include <cmath>
#include <exception>
#include <map>
#include <functional>
#include <vector>
#include <algorithm>
#include <numeric>
#include <sstream>
#include <type_traits>
#include <Eigen/Eigen>

#include <rclcpp/rclcpp.hpp>
#include <ament_index_cpp/get_package_share_directory.hpp>
#include <controller_interface/controller_interface.hpp>
#include <controller_interface/helpers.hpp>
#include <controller_manager_msgs/srv/list_hardware_interfaces.hpp>
#include <hardware_interface/loaned_command_interface.hpp>
#include <hardware_interface/types/hardware_interface_type_values.hpp>
#include <rclcpp_lifecycle/state.hpp>
#include "lifecycle_msgs/msg/state.hpp"

#include <franka_semantic_components/franka_robot_model.hpp>
#include <franka_semantic_components/franka_robot_state.hpp>
#include <franka/lowpass_filter.h>

#include <pinocchio/algorithm/kinematics.hpp>
#include <pinocchio/algorithm/frames.hpp>
#include <pinocchio/algorithm/rnea.hpp>
#include <pinocchio/algorithm/crba.hpp>
#include <pinocchio/algorithm/jacobian.hpp>
#include <pinocchio/parsers/urdf.hpp>

// auto-generated by generate_parameter_library
#include "fr3_husky_controller/fr3_controller_parameters.hpp"

#include <fr3_husky_controller/utils/dyros_math.h>
#include <fr3_husky_controller/utils/robot_utils.hpp>

#define FR3_DOF 7

namespace ConsoleColor
{
    inline constexpr const char* RESET = "\033[0m";
    inline constexpr const char* BLUE  = "\033[34m";
    inline constexpr const char* YELLOW= "\033[33m";
    inline constexpr const char* RED   = "\033[31m";
}

#define LOGI(node, fmt, ...) RCLCPP_INFO((node)->get_logger(),  (std::string(ConsoleColor::BLUE)   + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGW(node, fmt, ...) RCLCPP_WARN((node)->get_logger(),  (std::string(ConsoleColor::YELLOW) + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)
#define LOGE(node, fmt, ...) RCLCPP_ERROR((node)->get_logger(), (std::string(ConsoleColor::RED)    + fmt + ConsoleColor::RESET).c_str(), ##__VA_ARGS__)

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;
using fr3_controller::ParamListener;
using fr3_controller::Params;

namespace fr3_husky_controller
{
class TestFr3Controller : public controller_interface::ControllerInterface
{
    inline static constexpr size_t kPositionIndex = 0;
    inline static constexpr size_t kVelocityIndex = 1;
    inline static constexpr size_t kEffortIndex   = 2;

public:
    // ========================================================================
    // ============================ Core Functions ============================
    // ========================================================================
    [[nodiscard]] controller_interface::InterfaceConfiguration state_interface_configuration() const override;
    [[nodiscard]] controller_interface::InterfaceConfiguration command_interface_configuration() const override;
    CallbackReturn on_init() override;
    CallbackReturn on_configure(const rclcpp_lifecycle::State& previous_state) override;
    CallbackReturn on_activate(const rclcpp_lifecycle::State& previous_state) override;
    CallbackReturn on_deactivate(const rclcpp_lifecycle::State& previous_state) override;
    controller_interface::return_type update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

private:
    // ========================================================================
    // ====================== Main Controller Functions =======================
    // ========================================================================
    void writeCommandInterfaces(const Eigen::VectorXd& command);
    void updateJointStates();
    void updateRobotData();
    void haltCommands();
    void setInitfromCurrent();

    // ========================================================================
    // =========================== Franka robot Data ==========================
    // ========================================================================
    std::vector<std::unique_ptr<franka_semantic_components::FrankaRobotModel>> franka_robot_model_;
    pinocchio::Model pin_model_;
    pinocchio::Data pin_data_;
    bool use_pin_{false};

    // Precomputed pinocchio indices/IDs
    std::map<std::string, std::array<int, FR3_DOF>> pin_q_idx_;
    std::map<std::string, std::array<int, FR3_DOF>> pin_v_idx_;
    std::map<std::string, pinocchio::FrameIndex>    pin_link0_id_;
    std::map<std::string, pinocchio::FrameIndex>    pin_ee_id_;
    std::map<std::string, size_t>                   pin_ee_robot_idx_;
    Eigen::VectorXd q_pin_;
    Eigen::VectorXd qdot_pin_;
    Eigen::MatrixXd J_full_;

    // ========================================================================
    // ======================= Manipulator State Data =========================
    // ========================================================================
    std::vector<std::string> robot_names_;

    std::map<std::string, Eigen::Vector<double, FR3_DOF>> q_init_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qdot_init_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qddot_init_;
    Eigen::VectorXd q_total_init_;
    Eigen::VectorXd qdot_total_init_;
    Eigen::VectorXd qddot_total_init_;

    std::map<std::string, Eigen::Vector<double, FR3_DOF>> q_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qdot_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qddot_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> torque_;
    Eigen::VectorXd q_total_;
    Eigen::VectorXd qdot_total_;
    Eigen::VectorXd qddot_total_;
    Eigen::VectorXd torque_total_;

    std::map<std::string, Eigen::Vector<double, FR3_DOF>> q_desired_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qdot_desired_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> qddot_desired_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> torque_desired_;
    Eigen::VectorXd q_desired_total_;
    Eigen::VectorXd qdot_desired_total_;
    Eigen::VectorXd qddot_desired_total_;
    Eigen::VectorXd torque_desired_total_;

    // Dynamics
    std::map<std::string, Eigen::Matrix<double, FR3_DOF, FR3_DOF>> M_;
    std::map<std::string, Eigen::Matrix<double, FR3_DOF, FR3_DOF>> M_inv_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> c_;
    std::map<std::string, Eigen::Vector<double, FR3_DOF>> g_;
    Eigen::MatrixXd M_total_;
    Eigen::MatrixXd M_inv_total_;
    Eigen::VectorXd c_total_;
    Eigen::VectorXd g_total_;

    // ========================================================================
    // ============================= Task Space Data ==========================
    // ========================================================================
    std::vector<std::string> ee_names_;

    std::map<std::string, Eigen::Affine3d> x_init_;
    std::map<std::string, Eigen::Vector6d> xdot_init_;
    std::map<std::string, Eigen::Affine3d> x_;
    std::map<std::string, Eigen::Vector6d> xdot_;
    std::map<std::string, Eigen::Matrix<double, 6, FR3_DOF>> J_;
    std::map<std::string, Eigen::Affine3d> x_desired_;
    std::map<std::string, Eigen::Vector6d> xdot_desired_;

    // ========================================================================
    // =========================== Controller data ============================
    // ========================================================================
    size_t num_robots_{0};
    double dt_{0.0};
    double play_time_{0.0};
    double control_start_time_{0.0};
    const std::string arm_id_{"fr3"};

    // ========================================================================
    // ============================== Parameters ==============================
    // ========================================================================
    std::shared_ptr<ParamListener> param_listener_;
    Params params_;
    size_t manipulator_dof_{0};

    // ========================================================================
    // ============================ Mutex & Thread ============================
    // ========================================================================
    std::mutex robot_data_mutex_;

    // ========================================================================
    // ============================ Interfaces Setup ==========================
    // ========================================================================
    const std::vector<std::string> allowed_interface_types_ = {
        hardware_interface::HW_IF_POSITION,
        hardware_interface::HW_IF_VELOCITY,
        hardware_interface::HW_IF_EFFORT,
    };

    struct JointHandle
    {
        std::vector<std::reference_wrapper<hardware_interface::LoanedStateInterface>> state;
        std::reference_wrapper<hardware_interface::LoanedCommandInterface> command;
        explicit JointHandle(std::reference_wrapper<hardware_interface::LoanedCommandInterface> cmd)
        : command(cmd) {}
    };

    mutable std::vector<JointHandle> registered_manipulator_joint_handles_;

    bool has_position_state_interface_   = false;
    bool has_velocity_state_interface_   = false;
    bool has_effort_state_interface_     = false;
    bool has_position_command_interface_ = false;
    bool has_velocity_command_interface_ = false;
    bool has_effort_command_interface_   = false;

    bool is_halted_       = false;
    bool halt_initialized_ = false;
    std::map<std::string, double> halt_position_;
};

}  // namespace fr3_husky_controller
