controller_names:
  - fr3_husky_joint_trajectory_controller

fr3_husky_joint_trajectory_controller:
  action_ns: ""
  type: FollowJointTrajectory
  default: true
  joints:
    - right_fr3_joint1
    - right_fr3_joint2
    - right_fr3_joint3
    - right_fr3_joint4
    - right_fr3_joint5
    - right_fr3_joint6
    - right_fr3_joint7
